# Generated by Django 5.1.2 on 2024-10-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bankloan',
            fields=[
                ('Name', models.CharField(max_length=6)),
                ('Loan_type', models.CharField(max_length=10)),
                ('Loan_amount', models.IntegerField(primary_key='Loan_amount', serialize=False)),
                ('Rate_of_intrest', models.FloatField()),
                ('Duration', models.CharField(max_length=10)),
                ('EMI', models.IntegerField()),
                ('Total_amount', models.IntegerField()),
                ('Intrest', models.IntegerField()),
            ],
        ),
    ]
